name: Build and Deploy Order API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          apt update && apt install -y curl openssh-client unzip
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          mv cloudflared /usr/local/bin/

      - name: Setup SSH key
        run: |
          mkdir -p /tmp/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/.ssh/id_rsa
          chmod 600 /tmp/.ssh/id_rsa
          ssh-keyscan -H ssh.cuder.xyz >> /tmp/.ssh/known_hosts || true

      - name: Debug SSH key setup
        run: |
          ls -la /tmp/.ssh
          cat /tmp/.ssh/id_rsa || echo "Private key is missing or unreadable"
          ssh -i /tmp/.ssh/id_rsa -o StrictHostKeyChecking=no phongle@ssh.cuder.xyz "echo 'SSH connection successful'"

      - name: Copy deployment.yaml to server
        run: |
          scp -i /tmp/.ssh/id_rsa -o StrictHostKeyChecking=no \
              -o ProxyCommand="cloudflared access ssh --hostname ssh.cuder.xyz" \
              ./k8s/deployment.yaml phongle@ssh.cuder.xyz:/tmp/deployment.yaml

      - name: Apply Kubernetes deployment
        run: |
          ssh -i /tmp/.ssh/id_rsa -o StrictHostKeyChecking=no \
              -o ProxyCommand="cloudflared access ssh --hostname ssh.cuder.xyz" \
              phongle@ssh.cuder.xyz \
              "kubectl apply -f /tmp/deployment.yaml && \
               kubectl rollout status deployment/order-api --timeout=60s"