name: Build and Deploy Order API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/

      - name: Setup SSH key
        run: |
          mkdir -p /tmp/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/.ssh/id_rsa
          chmod 600 /tmp/.ssh/id_rsa

      - name: Configure SSH with ProxyCommand
        run: |
          mkdir -p ~/.ssh
          echo "Host ssh.cuder.xyz
            User phongle
            ProxyCommand cloudflared access ssh --hostname %h
            IdentityFile /tmp/.ssh/id_rsa
            StrictHostKeyChecking no
          " > ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Copy deployment.yaml to server
        run: |
          scp ./k8s/deployment.yaml ssh.cuder.xyz:/tmp/deployment.yaml

      - name: Apply Kubernetes deployment
        run: |
          ssh ssh.cuder.xyz "kubectl apply -f /tmp/deployment.yaml && \
                             kubectl rollout status deployment/order-api --timeout=60s"